# train config
train_manifest = "data/train.datalist.csv"
val_manifest = "data/val.datalist.csv"
color_mode = "rgb"
patch_size = 128
target_value = "rgb_psnr"
watched_best = ['rgb_psnr']
status = ['y_psnr', 'y_psnr_gain', 'rgb_psnr', 'rgb_psnr_gain']
epochs = 10
batch_size = 8
lr = 0.001
runs_dir = "runs"
num_workers = 2
