# train config
train_manifest = "data/train.datalist.csv"
val_manifest = "data/test.datalist.csv"
color_mode = "rgb"
patch_size = 128
target_value = "rgb_psnr"
watched_best = ['rgb_psnr_gain', 'rgb_ssim_gain']
status = ['y_psnr', 'y_psnr_gain', 'rgb_psnr', 'rgb_psnr_gain', 'rgb_ssim', 'rgb_ssim_gain']
seed = 37
epochs = 50
batch_size = 32
lr = 0.001
lr_min = 0.000001
runs_dir = "runs"
num_workers = 2
